language: generic

matrix:
  include:
    - os: osx
      env: COMPILER=4.11.1
    - os: freebsd
      env: COMPILER=4.11.1
    - os: linux
      env: COMPILER=4.11.1 REVDEPS=yes
    - os: linux
      env: COMPILER=4.02.3

before_script:
  - |
    if [ "$TRAVIS_EVENT_TYPE" == cron ]
    then
      rm -rf ~/.opam
      rm -rf ./_opam
      rm -rf ./_cache
    fi
  - VERSION=2.0.6
  - |
    case "$TRAVIS_OS_NAME" in
      linux) OS=linux;;
        osx) OS=macos;;
    freebsd) OS=openbsd;;
          *) echo Unsupported system $TRAVIS_OS_NAME; exit 1;;
    esac
  - FILENAME=opam-$VERSION-x86_64-$OS
  - wget https://github.com/ocaml/opam/releases/download/$VERSION/$FILENAME
  - sudo mv $FILENAME /usr/local/bin/opam
  - sudo chmod a+x /usr/local/bin/opam
  - opam init -y --bare --disable-sandboxing --disable-shell-hook
  - |
    if [ ! -d _opam/bin ]
    then
      rm -rf _opam
      opam switch create . $COMPILER $REPOSITORIES --no-install
    fi
  - eval `opam env`
  - ocamlc -config
  - opam --version
  - ocaml -version
  - cc --version || true
  - gcc --version || true
  - clang --version || true
  - python3 --version
  - |
    if [ ! -d _cache/_build ]
    then
      opam install -y --deps-only --with-test ./luv.opam
    fi
  - opam list

  # Work around https://github.com/ocaml/dune/issues/4121.
  - git clone https://github.com/libuv/libuv.git
  - sudo mv libuv/include/* /usr/include/
  - rm -rf libuv

script:
  - |
    case "$TRAVIS_OS_NAME" in
      freebsd) MAKE=gmake;;
      *) MAKE=make;;
    esac
  - ${MAKE} check-ejected-build
  - '[ ! -d _cache/_build ] || cp -r _cache/_build .'
  - ${MAKE}
  - ${MAKE} test

  # Undo workaround for https://github.com/ocaml/dune/issues/4121.
  - rm -f /usr/include/uv.h

  - '[ "$REVDEPS" != yes ] || ${MAKE} --output-sync=target examples'
  - mkdir -p _cache
  - '[ -d _cache/_build ] || cp -r _build _cache'
  - '[ "$REVDEPS" != yes ] || ${MAKE} test-installation-ci'
  - opam lint .

before_cache:
  - opam clean

cache:
  directories:
    - $HOME/.opam
    - ./_opam
    - ./_cache

notifications:
  email:
    on_success: always
    on_failure: always
