version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "8080:8080"
    links:
      - dream
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./assets:/www/assets

  dream:
    build: .
    restart: always
    logging:
      driver: ${LOGGING_DRIVER:-json-file}
