name: CI
on: [push, pull_request]
jobs:
  debian_500_trunk:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:debian-11-ocaml-5.00
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - name: ~~~ Checkout code ~~~
      uses: actions/checkout@v2
    - name: ~~~ Install Dune ~~~
      run: opam install dune.2.9.2
    - name: ~~~ Build the duniverse (or at least parts of it) ~~~
      run: opam exec -- dune runtest