name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  debian_500_trunk:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:debian-11-ocaml-5.00
      env:
        HOME: /home/opam
      options: --user 1000 --ulimit memlock=819200000:819200000
    env:
      HOME: /home/opam
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: mkdir -p /home/opam/package
    - name: Cloning
      run: git clone https://${{ secrets.GithubToken }}@github.com/$GITHUB_REPOSITORY . && git checkout ${{ github.event.pull_request.head.sha }}
      working-directory: /home/opam/package
      if: ${{ github.event_name == 'pull_request' }}
    - name: ~~~ Cloning ~~~
      run: git clone https://${{ secrets.GithubToken }}@github.com/$GITHUB_REPOSITORY .
      working-directory: /home/opam/package
      if: ${{ github.event_name == 'push' }}
    - name: ~~~ Install dune ~~~
      run: opam install dune.2.9.2
    - name: ~~~ Build with the Duniverse ~~~
      run: opam exec -- dune runtest